### ISSUE TITLE
When using parallel run extension the main concordion spec succeeds without waiting for the test to finish.

### ISSUE THREAD

**Issue by ghost** [concordion/concordion-parallel-run-extension#3]
When launching a main spec which imports other specs through the parallel run concordion extension the test succeeds even if the report log says there were failures. Seems the main concordion spec succeeds without waiting for all the spec test's to finish.

**Comment by nigelcharman** [comment]
This appears to be due to the new "example" support, which is also used for the "outer" example (for all commands run outside of examples). A separate JUnit test is created for each example.

The parallel runner waits for completion of the specification, but not the example. Since the example returns immediately, it returns success before the child thread running the specification has completed.

Changing the implementation to wait for each example may provide a fix. I'll look at this over the next week.
